### ISSUE TITLE
Even Sample code doesn't work

### ISSUE THREAD

**Issue by RushilRobotics** [FRC4564/Xbox#10]
Traceback (most recent call last):
  File "C:\Users\shahr\Downloads\Xbox-master\Xbox-master\sample.py", line 21, in <module>
    joy = xbox.Joystick()
  File "C:\Users\shahr\Downloads\Xbox-master\Xbox-master\xbox.py", line 44, in __init__
    self.proc = subprocess.Popen(['xboxdrv','--no-uinput','--detach-kernel-driver'], stdout=subprocess.PIPE, bufsize=0)
  File "C:\Users\shahr\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\shahr\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by FRC4564** [comment]
This Python class requires xboxdrv to function, which is a Linux-only application.  Based on you traceback, you are attempting to run this on a Windows machine.  You'll need to find an alternative solution for using the Xbox controller under Windows.
